
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_manager_demo
    username: root
    password: 123456

  jpa:
    properties:
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true